/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hidraulicagrupo;
import java.text.DecimalFormat;
import javax.swing.UIManager;

/**
 *
 * @author jean7
 */
public class FrameHidraulica extends javax.swing.JFrame {

    /**
     * Creates new form FrameHidraulica
     */
    
    public FrameHidraulica() {
        initComponents();
        this.setTitle("Calculadora Mannin Darcy Weisbach");
    }
    public static void main(String []args){
        
        
    try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameHidraulica().setVisible(true);
            }
        });
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameHidraulica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameHidraulica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameHidraulica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameHidraulica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQ = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtZ = new javax.swing.JTextField();
        txtM = new javax.swing.JTextField();
        txtS = new javax.swing.JTextField();
        txtE = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtObs2 = new javax.swing.JLabel();
        txtResManY = new javax.swing.JLabel();
        txtResManV = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtObs = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtResColY = new javax.swing.JLabel();
        txtResColV = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtObsD = new javax.swing.JLabel();
        txtObsD2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtDf = new javax.swing.JLabel();
        txtDRE = new javax.swing.JLabel();
        txtDA = new javax.swing.JLabel();
        txtDERR = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Caudal");

        jLabel2.setText("Ancho del canal");

        jLabel3.setText("Pendiente lateral del canal");

        jLabel4.setText("Coeficiente de Manning");

        jLabel5.setText("Pendiente longitudinal del canal");

        jLabel6.setText("Rugosidad absoluta");

        txtQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQActionPerformed(evt);
            }
        });
        txtQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQKeyTyped(evt);
            }
        });

        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        txtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBKeyTyped(evt);
            }
        });

        txtZ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtZKeyTyped(evt);
            }
        });

        txtM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMKeyTyped(evt);
            }
        });

        txtS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSActionPerformed(evt);
            }
        });
        txtS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSKeyTyped(evt);
            }
        });

        txtE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEKeyTyped(evt);
            }
        });

        btnCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculator2.png"))); // NOI18N
        btnCalc.setText("Calcular Manning y Darcy");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        jLabel14.setText("[m^3/s]");

        jLabel15.setText("[m]");

        jLabel18.setText("Z=");

        jLabel19.setText("Q=");

        jLabel20.setText("b=");

        jLabel21.setText("n=");

        jLabel22.setText("[m/m]");

        jLabel23.setText("e=");

        jLabel24.setText("[mm]");

        jLabel25.setText("Este programa calcula las características del caudal utilizando la ecuación de Manning y de Colebrook-White.");

        jLabel17.setText("S=");

        jLabel7.setText("Resultados Manning");

        jLabel8.setText("Altura del canal (m)");

        jLabel9.setText("Velocidad (m/s)");

        txtObs2.setText("-");

        txtResManY.setText("0");

        txtResManV.setText("0");

        jLabel10.setText("Observaciones");

        txtObs.setText("-");

        jLabel11.setText("Resultados Darcy");

        jLabel12.setText("Altura del canal (m)");

        jLabel13.setText("Velocidad (m/s)");

        txtResColY.setText("0");

        txtResColV.setText("0");

        jLabel16.setText("Observaciones");

        txtObsD.setText("-");

        txtObsD2.setText("-");

        jLabel26.setText("Factor fricción");

        jLabel27.setText("%Error con Manning");

        jLabel28.setText("Froude");

        jLabel29.setText("Area [m^2]");

        txtDf.setText("0");

        txtDRE.setText("0");

        txtDA.setText("0");

        txtDERR.setText("0");

        jLabel30.setText("Elaborado por: Jean Cedeño- Flor Benalcazar - Johanna Borja");

        jLabel31.setText(" Luis Capa- Ambar Escobar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtResManV)
                                            .addComponent(txtResManY))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtObs2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResColV)
                            .addComponent(txtResColY)
                            .addComponent(txtObsD)
                            .addComponent(txtObsD2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDERR)
                            .addComponent(txtDA)
                            .addComponent(txtDRE)
                            .addComponent(txtDf))))
                .addGap(234, 234, 234))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtResManY))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtResManV)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtResColY))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtResColV))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtObs)
                        .addComponent(jLabel26))
                    .addComponent(jLabel10)
                    .addComponent(txtDf))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDRE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDA)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtDERR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtObsD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObsD2)))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtObs2)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addContainerGap(8, Short.MAX_VALUE))))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar2.png"))); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtQ)
                                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel22)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCalc)
                                    .addGap(94, 94, 94)
                                    .addComponent(jButton1)))
                            .addComponent(jLabel25))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalc)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
       if (!(txtQ.getText().isEmpty() ||txtB.getText().isEmpty() ||
               txtZ.getText().isEmpty() || txtM.getText().isEmpty() || txtE.getText().isEmpty())){
       Double Q = Double.parseDouble(txtQ.getText());
       Double B = Double.parseDouble(txtB.getText());
       Double Z = Double.parseDouble(txtZ.getText());
       Double S = Double.parseDouble(txtS.getText());
       Double N = Double.parseDouble(txtM.getText());
       Double E = Double.parseDouble(txtE.getText());
       
       //calculo segun Manning
       Double yn=0.01; //Valor inicial
       Double error=100.0;
       Double tolerancia=(1.0e-6);
       int numIterac=0;
       Double AreaN=null;
       Double PerimN;
       Double RadioHN=null;
       Double EspejoN;
       Double DiamHN;
       Double Func_Manning;
       Double Deriv_func;
       Double yi;
       
       while(error > tolerancia && numIterac <= 10000){
           AreaN= (B*yn+Z*yn*yn);
           PerimN=(B+(yn*2*Math.sqrt(1+(Z*Z))));
           EspejoN=(B+2*Z*yn);
           RadioHN= AreaN/PerimN;
           DiamHN=AreaN/EspejoN;
           Func_Manning= (1/N)*Math.sqrt(S)*AreaN*Math.pow(RadioHN, 2.0/3.0)-Q;
           Deriv_func= (Math.sqrt(S)*(1/N)*(Math.pow(RadioHN, 2.0/3.0)*EspejoN)+(EspejoN/PerimN)-((2*yn*RadioHN)/PerimN));
           yi=yn-(Func_Manning/Deriv_func);
           error=Math.abs((yi-yn)/yn);
           yn=yi;
           numIterac++;
       }
       Double Calado=(double) Math.round(yn*10000.0)/10000;
       Double AreaH=(B+(Z*Calado))*Calado;
       Double Vel=(double) Math.round((Q/AreaH)*10000.0)/10000;
       Double T=B+(2*Z*Calado);
       Double F=Vel/Math.sqrt(9.81*(AreaH/T));
       
       txtResManY.setText("El calado es: "+ Calado + "[m]");
       txtResManV.setText("La velocidad es: "+ Vel + "[m/s]");
       
       //observaciones
       String observ="";
       String observ1="";
       if(F<1){
       observ= observ+"Flujo en régimen subcrítico ";
       }
       if(F>1){
       observ= observ+"Flujo en régimen supercrítico ";
       }
       if(Vel<0.5){
       observ1= observ1+"Riesgo de azolve de material Vel < 0.5 m/s";
       }
       if(Vel>2.5){
       observ1= observ1+"Velocidad alta. Por favor rediseñar el canal";
       }
       txtObs.setText(observ);
       txtObs2.setText(observ1);
       //Cálculo Darcy
       
       Double errorD=100.0;
       Double IteracD=0.0;
       Double yd=0.01;
       Double f=0.01;
       Double AreaD;
       Double PerimD;
       Double RadioHD;
       Double DH = null;
       Double U=1.007e-6;
       Double VelD;
       Double Re=null;
       Double izqEc;
       Double derEc;
       Double EV=E/1000.0;
       Double dif=1000.0;
       while (errorD>tolerancia && IteracD <= 1*10e7){
            AreaD= (B*yd+Z*yd*yd);
            PerimD=(B+(yd*2*Math.sqrt(1+(Z*Z))));
            RadioHD=(AreaD/PerimD);
            DH=4.0*RadioHD;
            VelD=Q/AreaD;
            Re=(VelD*DH)/U;
            
            izqEc=(1/Math.sqrt(f));
            derEc=(-2*Math.log10((EV/(3.71*DH))+(2.51/(Re*Math.sqrt(f)))));
            f=(8*9.81*RadioHD*S)/(VelD*VelD);
            errorD=Math.abs(derEc-izqEc);
            if(dif>errorD){
                yd=yd+0.000001;
            }
            
            else if (errorD <= 1*10e-4 || (Math.abs(dif-errorD)< 10e-7 && IteracD>10)){
            IteracD=1*10e7;
            }
            IteracD++;
            
            dif=errorD;
            }
       Double CaladoD=(double) Math.round(yd*10000.0)/10000;
       Double AreaHd=(B+(Z*CaladoD))*CaladoD;
       VelD=(double) Math.round((Q/AreaHd)*10000.0)/10000;
       Double TD=B+(2*Z*CaladoD);
       Double FD=Vel/Math.sqrt(9.81*(AreaHd/T));
       Double ErrorConManning=(Math.abs(CaladoD-Calado)/Calado)*100;
       Double ErrorConManningR=(double)Math.round(ErrorConManning*100.0)/100;
       Double fRes=(double) Math.round(f*1000.0)/1000;
       Double AreaHdRes=(double) Math.round(AreaHd*1000.0)/1000;
       txtResColY.setText("La altura es: "+CaladoD+ "[m]" );
       txtResColV.setText("La velocidad es: "+VelD+ "[m/s]" );
       txtDf.setText(""+fRes);
       DecimalFormat formato = new DecimalFormat("0.###E0");
       String ReA=formato.format(Re).replace("E", "x10^");
       txtDRE.setText(""+ReA);
       txtDA.setText(""+AreaHdRes + "[m^2]");
       txtDERR.setText(""+ErrorConManningR+"%");
       
       //Mostrar observaciones
       
       String observD="";
       String observD1="";
       if(FD<1){
       observD= observD+"Flujo en régimen subcrítico ";
       }
       if(FD>1){
       observD= observD+"Flujo en régimen supercrítico ";
       }
       if(VelD<0.5){
       observD1= observD1+"Riesgo de azolve de material Vel < 0.5 m/s";
       }
       if(VelD>2.5){
       observD1= observD1+"Velocidad alta. Por favor rediseñar el canal";
       }
       txtObsD.setText(observD);
       txtObsD2.setText(observD1);
       }
       else{
           txtObs.setText("Se requieren todos los campos");
           txtObsD.setText("Se requieren todos los campos");
       }
       
    }//GEN-LAST:event_btnCalcActionPerformed

    private void txtQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQActionPerformed

    private void txtSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtQ.setText("");
        txtB.setText("");
        txtZ.setText("");
        txtS.setText("");
        txtM.setText("");
        txtE.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtQKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQKeyTyped
        
        int key = evt.getKeyChar();

        boolean numeros = key >= 42 && key <= 57;

        if (txtQ.getText().trim().length() == 10 ||txtQ.getText().length() >= 10 ||!numeros ) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQKeyTyped

    private void txtBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 42 && key <= 57;

        if (txtB.getText().trim().length() == 10 ||txtB.getText().length() >= 10 ||!numeros ) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBKeyTyped

    private void txtZKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 42 && key <= 57;

        if (txtZ.getText().trim().length() == 10 ||txtZ.getText().length() >= 10 ||!numeros ) {
            evt.consume();
        }
    }//GEN-LAST:event_txtZKeyTyped

    private void txtMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 42 && key <= 57;

        if (txtM.getText().trim().length() == 10 ||txtM.getText().length() >= 10 ||!numeros ) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMKeyTyped

    private void txtSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 42 && key <= 57;

        if (txtS.getText().trim().length() == 10 ||txtS.getText().length() >= 10 ||!numeros ) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSKeyTyped

    private void txtEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 42 && key <= 57;

        if (txtE.getText().trim().length() == 10 ||txtE.getText().length() >= 10 ||!numeros ) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtB;
    private javax.swing.JLabel txtDA;
    private javax.swing.JLabel txtDERR;
    private javax.swing.JLabel txtDRE;
    private javax.swing.JLabel txtDf;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextField txtM;
    private javax.swing.JLabel txtObs;
    private javax.swing.JLabel txtObs2;
    private javax.swing.JLabel txtObsD;
    private javax.swing.JLabel txtObsD2;
    private javax.swing.JTextField txtQ;
    private javax.swing.JLabel txtResColV;
    private javax.swing.JLabel txtResColY;
    public javax.swing.JLabel txtResManV;
    public javax.swing.JLabel txtResManY;
    private javax.swing.JTextField txtS;
    private javax.swing.JTextField txtZ;
    // End of variables declaration//GEN-END:variables
}
